#!/usr/bin/env bash

# Check if current directory is inside a git repository
is_git_repo() {
  git rev-parse --show-toplevel > /dev/null 2>&1
  result=$?
  if test $result != 0; then
    >&2 echo 'Not a git repo!'
    exit $result
  fi
}

is_git_repo

default_branches=$(git config --get init.defaultBranch)
git branch -vv |
    grep gone |
    cut -c2- |
    grep -v "$default_branches" |
    perl -ane 'print "@F[0]\n"' |
    xargs -r git branch -D
