#!perl

use Dir::GitSync;
use Pod::Usage;

my ($dir) = @ARGV;

if ( not defined $dir ) {
    pod2usage(
        -message => "no source directory given",
        -exitval => $exit_status,
        -verbose => 1
    );
}

my $repo = Dir::GitSync->repository( Directory => $dir );
if ( $repo->try_create_commit() ) {
    $repo->store();
}
else {
    $repo->fetch();
}

=head1 NAME

mk-sync-dir - Synchroize directories using Git

=head1 SYNOPSIS

mk-sync-dir <repository>

=head1 DESCRIPTION

Syncronize a directory using git(1) by:

1. Create a commit with all new, modified, renamed, and deleted files.

2. Pull and rebase the branch on the remote repository.

3. Push the resulting branch to the remote repository.

=head1 AUTHOR

Mats Kindahl <mats@kindahl.net>

=head1 LICENSE

Apache License 2.0

=cut

exit(0);
